# Generated by Django 3.2.18 on 2023-04-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('rasm', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('narx', models.IntegerField()),
                ('chegirma', models.IntegerField()),
                ('brend', models.CharField(max_length=25)),
                ('batafsil', models.TextField()),
                ('rasm', models.FileField(blank=True, null=True, upload_to='')),
                ('holat', models.CharField(max_length=25)),
                ('mavjud', models.BooleanField()),
                ('bolim_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('reyting', models.CharField(max_length=25)),
                ('sana', models.DateTimeField()),
                ('mahsulot_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot')),
                ('profil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
            ],
        ),
    ]
