# Generated by Django 3.2.18 on 2023-04-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='sotuvchi_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.profil'),
        ),
    ]
