# Generated by Django 3.2.18 on 2023-04-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_mahsulot_sotuvchi_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='reyting',
            field=models.SmallIntegerField(max_length=25),
        ),
    ]
