# Generated by Django 3.2.18 on 2023-04-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_izoh_reyting'),
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savat',
            name='mahsulot_fk',
        ),
        migrations.RemoveField(
            model_name='savat',
            name='miqdor',
        ),
        migrations.RemoveField(
            model_name='savat',
            name='yetkazish_kuni',
        ),
        migrations.AddField(
            model_name='savat',
            name='ochilgan_sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Savatitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField(default=1)),
                ('yetkazish_kuni', models.PositiveSmallIntegerField(default=4)),
                ('umumiy_summa', models.IntegerField(blank=True, null=True)),
                ('mahsulot_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot')),
                ('savat_fl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma.savat')),
            ],
        ),
    ]
