# Generated by Django 3.2.18 on 2023-04-10 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('rasm', models.FileField(blank=True, null=True, upload_to='')),
                ('tel', models.CharField(max_length=13)),
                ('tugulgan_yil', models.DateField()),
                ('jins', models.CharField(max_length=6)),
                ('shaxar', models.CharField(max_length=50)),
                ('user_fk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
